# before_script:
#   - docker info
#   - docker-compose version

# stages:
#   - deploy

# deploy:
#   stage: deploy
#   script:
#     - echo $ENV | sed 's/ /\n/g' > .env
#     - docker-compose --env-file .env build || exit 1
#     - docker-compose up -d --build --remove-orphans || exit 1
#   environment:
#     name: production
#     url: http://165.22.106.189
#   only:
#     - staging-main
#   tags:
#     - deployment
