stages:          
  - build
  
build-job:      
  stage: build
  tags:
    - development  # เพิ่ม Tag ให้ตรงกับ Runner
  script:
    - echo $ENV | sed 's/ /\n/g' > .env
    - cat .env
    - docker compose up -d --build
