# nginx config doesn't work yet
# only the sveltekit-app service works

version: '3.0'

services:
  sveltekit-app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
  ngx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - /root/nginx/conf.d:/etc/nginx/conf.d:ro
